<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Katherine Li (kkl5524)">
<meta name="dcterms.date" content="2025-08-13">

<title>Course Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="kkl5524Stat184CourseProject_files/libs/clipboard/clipboard.min.js"></script>
<script src="kkl5524Stat184CourseProject_files/libs/quarto-html/quarto.js"></script>
<script src="kkl5524Stat184CourseProject_files/libs/quarto-html/popper.min.js"></script>
<script src="kkl5524Stat184CourseProject_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="kkl5524Stat184CourseProject_files/libs/quarto-html/anchor.min.js"></script>
<link href="kkl5524Stat184CourseProject_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="kkl5524Stat184CourseProject_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="kkl5524Stat184CourseProject_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="kkl5524Stat184CourseProject_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="kkl5524Stat184CourseProject_files/libs/bootstrap/bootstrap-c0367b04c37547644fece4185067e4a7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="kkl5524Stat184CourseProject.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li><li><a href="kkl5524Stat184CourseProject.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Course Project</h1>
<p class="subtitle lead">STAT 184</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Katherine Li (kkl5524) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 13, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The two questions that this exploratory data analysis aims to answer are:<br>
</p>
<ol type="1">
<li>Is there a <strong>correlation</strong> between international K-pop streaming trends and international tourist arrivals to South Korea?<br>
</li>
<li>Which regions show the <strong>strongest tendencies</strong> toward increased travel to South Korea based off of trends in K-pop releases?<br>
</li>
</ol>
<p>Given these guiding questions, the hypotheses that will frame the visualizations below are:<br>
</p>
<ol type="1">
<li>The correlation coefficient p is zero (null hypothesis H<sub>0</sub>: p = 0).<br>
</li>
<li>Asia will have the strongest tendencies toward increased travel, as the continent demonstrating the “fastest growth in leisure spending” (Our Culture Mag &amp; Partners, 2025).<br>
<br>
</li>
</ol>
</section>
<section id="background-information" class="level2">
<h2 class="anchored" data-anchor-id="background-information">Background Information</h2>
<p>Originally starting in the 1990s as a musical subculture in South Korea, K-pop (or Korean Pop) has experienced an international boom in popularity, generating billions of dollars every year. It stands to reason that after becoming such a global sensation, K-pop has not only impacted South Korea’s economy but sparked interest in Korean culture.<br>
</p>
<p>This exploratory data analysis aims to analyze the <strong>fluctuations in inbound tourist arrivals</strong> to South Korea and compare them to K-pop releases to identify a trend between the two.<br>
</p>
<p>The possible uses of this information would be useful for businesses and companies that deal with incoming flow of tourists like hotels, ride-shares, airlines, and tour guides. Evidence of a greater trend could allow businesses to use K-pop releases as metrics to help plan future business activity.<br>
<br>
</p>
</section>
<section id="data-summary" class="level2">
<h2 class="anchored" data-anchor-id="data-summary">Data Summary</h2>
<section id="most-streamed-spotify-songs-2024---link" class="level3">
<h3 class="anchored" data-anchor-id="most-streamed-spotify-songs-2024---link">Most Streamed Spotify Songs 2024 - <a href="https://www.kaggle.com/datasets/nelgiriyewithana/most-streamed-spotify-songs-2024">Link</a></h3>
<p>This dataset comes from Kaggle, an online dataset repository. It contains data about streaming, engagement, rankings on the most widely used music streaming platforms, like YouTube, Apple Music, and the titular Spotify (<em>“datasets/Most Streamed Spotify Songs 2024.csv”</em>; Nelgiriyewithana, 2024). Originally gathered for music analysis and platform comparison, I will be using the number of Spotify Streams and YouTube likes as factors determining engagement and popularity of a track.<br>
</p>
<p>Spotify took the top spot of the music streaming industry, boasting <strong>640 million</strong> monthly active users worldwide and operating in 237 countries and territories as of 2025 (Spotify, 2025; Spotify, n.d.). The previous leader, Tencent, is largely based in China and its assorted regions, however its streaming data is unavailable to me at this time.<br>
</p>
<p>YouTube has remained the titan of the user-created long-form online video platform, dominating the market and only beat out by streaming services Netflix, Disney+, and Amazon Prime Video, all of whom do not have the option to stream K-pop music (Pangarkar, 2025).<br>
</p>
<p>The final attribute that I need from this data would be the data about the actual music: the title of the track, the artist’s name, and the release date. With this selection, each case is a single track and the data is easier to analyze.<br>
</p>
</section>
<section id="k-pop-groups-dataset---link" class="level3">
<h3 class="anchored" data-anchor-id="k-pop-groups-dataset---link">400+ K-Pop Groups Dataset - <a href="https://www.kaggle.com/datasets/nicolsalayoarias/kpop-groups-dataset">Link</a></h3>
<p>The K-pop group dataset also comes from Kaggle and provides data about many K-pop groups with the aim to provide a comprehensive resource for K-pop fans, researchers, and enthusiasts. This data provides a variety of data about different K-pop groups but main attribute of interest is the English name of the groups (<em>“datasets/kpopgroups.csv”</em>; Arias, 2023).<br>
</p>
<p>While debut year may have an impact, it was deemed negligible due to the low amount of international attention most groups get at conception. Before the international accessibility of K-pop information before 2024, groups acquired fame through their debut songs as opposed to any external marketing. Thus, I judged that <strong>only considering tracks attributed to each group</strong> would be sufficient representation. Since there is only one attribute, each case is the K-pop group listed.<br>
</p>
</section>
<section id="k-pop-idols-dataset---link" class="level3">
<h3 class="anchored" data-anchor-id="k-pop-idols-dataset---link">1700+ K-Pop Idols Dataset - <a href="https://www.kaggle.com/datasets/nicolsalayoarias/all-kpop-idols">Link</a></h3>
<p>Much like the K-pop group dataset, the K-pop idol dataset comes from Kaggle and contains data about a myriad of idols (<em>“datasets/kpopidolsv3.csv”</em>; Arias, 2023). Although K-pop groups create the bulk of the tracks, there is a recent trend of individual members from well-known groups like BTS, Blackpink, and TWICE producing solo albums and tracks that generate a lot of interest.<br>
</p>
<p>Therefore, the idols dataset is necessary to give a more complete view of the K-pop music landscape and make sure <strong>no large releases are unaccounted for</strong>.</p>
</section>
<section id="tourism-statistics-database---link" class="level3">
<h3 class="anchored" data-anchor-id="tourism-statistics-database---link">Tourism Statistics Database - <a href="https://www.unwto.org/tourism-statistics/tourism-statistics-database">Link</a></h3>
<p>Aside from K-pop, the other part of my analysis comes from tourism data from the United Nations World Tourism Organization (UNWTO), whose public dataset tracks annual international inbound arrivals to different countries in thousands and tracked by region from 1995 to 2022. The UNWTO is a specialized agency of the United Nations dedicated to universally accessible tourism, including data transparency.<br>
<br>
</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-unwto" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-unwto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Original_UN_Tourism_Data.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-unwto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Original UN Tourism Data
</figcaption>
</figure>
</div>
</div>
</div>
<p><br>
This dataset is incredibly important, as it shows the flow of travelers into Korea and will be how I analyze arrivals.<br>
</p>
<p>While originally formatted with variables acting as headings both horizontally and vertically (see <a href="#fig-unwto" class="quarto-xref">Figure&nbsp;1</a>), data cleaning was needed to properly format it for analysis. The first step was isolating the data about South Korea (listed as Republic of Korea) and reformatting it so that each case is the thousands of inbound tourists during a certain year and from a certain region.<br>
</p>
<p>Additionally, I combined the “South Asia” with the “East Asia and the Pacific” columns in order to account for following dataset. After undergoing this data cleaning, the new .csv file became easier to process in R (<em>“datasets/south korea visitor arrivals (thousands).csv”</em>).<br>
</p>
</section>
<section id="brief-vol.5-koreas-inbound-and-outbound-tourism-performance-in-2024" class="level3">
<h3 class="anchored" data-anchor-id="brief-vol.5-koreas-inbound-and-outbound-tourism-performance-in-2024">Brief Vol.5: Korea’s Inbound and Outbound Tourism Performance in 2024</h3>
<p>Although the UNWTO dataset was thorough, it misses data from after 2022. The Yanolja Research data adds the arrival population data for 2023 and 2024, which were added to the <em>“datasets/south korea visitor arrivals (thousands).csv</em> file as additional data points. While the data points for 2019 don’t match up exactly, the data from Yanolja Research is the best approximation available publicly at the moment (see <a href="#fig-yanolja" class="quarto-xref">Figure&nbsp;2</a>).<br>
<br>
</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-yanolja" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-yanolja-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Yanolja_Research_Chart.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-yanolja-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Yanolja Research Chart
</figcaption>
</figure>
</div>
</div>
</div>
<p><br>
</p>
</section>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<p>To start out, I need to filter out the cases from the Spotify 2024 data frame for only the tracks produced by K-pop groups or idols. To do this, I first joined together the K-pop group and idols data frames and kept all of the cases to get a <strong>complete list of K-pop artists</strong>.<br>
</p>
<p>After cleaning up the K-pop artist data frame, I clean the 2024 Spotify data to only keep the attributes track name, artist name, release year, number of Spotify streams, and number of YouTube likes.</p>
<p>Then, I join together the Spotify 2024 data with the K-pop artist information to <strong>filter out all extraneous cases</strong> (see <a href="#fig-kpop-spotify-table" class="quarto-xref">Figure&nbsp;3</a>).</p>
<div class="cell">
<div id="fig-kpop-spotify-table" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kpop-spotify-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 13%">
<col style="width: 39%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Artist Name</th>
<th style="text-align: left;">Track Name</th>
<th style="text-align: right;">Release Year</th>
<th style="text-align: right;">Spotify Streams</th>
<th style="text-align: right;">YouTube Likes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BTS</td>
<td style="text-align: left;">Dynamite</td>
<td style="text-align: right;">2020</td>
<td style="text-align: right;">1872577908</td>
<td style="text-align: right;">62311179</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jung Kook</td>
<td style="text-align: left;">Seven (feat. Latto) (Explicit Ver.)</td>
<td style="text-align: right;">2023</td>
<td style="text-align: right;">1673557134</td>
<td style="text-align: right;">10125293</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BTS</td>
<td style="text-align: left;">Butter</td>
<td style="text-align: right;">2021</td>
<td style="text-align: right;">1257974135</td>
<td style="text-align: right;">27744989</td>
</tr>
<tr class="even">
<td style="text-align: left;">BTS</td>
<td style="text-align: left;">Boy With Luv (feat. Halsey)</td>
<td style="text-align: right;">2019</td>
<td style="text-align: right;">1165842896</td>
<td style="text-align: right;">35291841</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jimin</td>
<td style="text-align: left;">Like Crazy</td>
<td style="text-align: right;">2023</td>
<td style="text-align: right;">1165398518</td>
<td style="text-align: right;">4239579</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kpop-spotify-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Top 5 Tracks by Spotify Streams (and associated data)
</figcaption>
</figure>
</div>
</div>
<p><br>
From this data, we can identify the most likely suspects for <strong>major fluctuations</strong> in foot traffic by grouping the data by the artists and seeing who generates the most amount of streams and likes (see <a href="#fig-kpop-popular-artist-table" class="quarto-xref">Figure&nbsp;4</a>).</p>
<div class="cell">
<div id="fig-kpop-popular-artist-table" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kpop-popular-artist-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Artist Name</th>
<th style="text-align: right;">Total Engagement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BTS</td>
<td style="text-align: right;">9992270097</td>
</tr>
<tr class="even">
<td style="text-align: left;">BLACKPINK</td>
<td style="text-align: right;">7488993372</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jimin</td>
<td style="text-align: right;">4683682209</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jung Kook</td>
<td style="text-align: right;">3858697464</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NewJeans</td>
<td style="text-align: right;">3604707139</td>
</tr>
<tr class="even">
<td style="text-align: left;">TWICE</td>
<td style="text-align: right;">2541336253</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IVE</td>
<td style="text-align: right;">1706428528</td>
</tr>
<tr class="even">
<td style="text-align: left;">LE SSERAFIM</td>
<td style="text-align: right;">1591756031</td>
</tr>
<tr class="odd">
<td style="text-align: left;">V</td>
<td style="text-align: right;">1461264324</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stray Kids</td>
<td style="text-align: right;">1335742282</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kpop-popular-artist-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Top 10 K-Pop Artists by Total Engagement on Spotify and YouTube
</figcaption>
</figure>
</div>
</div>
<p><br>
In addition to the K-pop data, there is also the tourism data. While the data is largely cleaned up already from previous processing, I still created an extra column that is the actual number of arrivals instead of just in thousands.</p>
<p>Thus, we are able to see the total amount of inbound tourists throughout the given data (see <a href="#fig-tourism-year-line" class="quarto-xref">Figure&nbsp;5</a>).<br>
<br>
</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-tourism-year-line" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tourism-year-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="kkl5524Stat184CourseProject_files/figure-html/fig-tourism-year-line-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tourism-year-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Note the dip in travel during 2020-2021 due to the COVID-19 pandemic
</figcaption>
</figure>
</div>
</div>
</div>
<p><br>
Now that we have the data laid out, the proper analysis can begin. For the K-pop data, we are able to see the number of tracks (see <a href="#fig-kpop-track-line" class="quarto-xref">Figure&nbsp;6</a>).<br>
<br>
</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-kpop-track-line" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kpop-track-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="kkl5524Stat184CourseProject_files/figure-html/fig-kpop-track-line-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kpop-track-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Years with fewer tracks may reflect incomplete data or delayed releases.
</figcaption>
</figure>
</div>
</div>
</div>
<p><br>
However, a major issue arises when solely considering the amount of songs produced because not all songs are created equal. Although to be on the list they have some degree of popularity, the tracks all have <strong>different amounts of engagement</strong>. The display of track distribution (see <a href="#fig-stream-track-histogram" class="quarto-xref">Figure&nbsp;7</a>) shows the inequality between tracks.<br>
<br>
</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-stream-track-histogram" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stream-track-histogram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="kkl5524Stat184CourseProject_files/figure-html/fig-stream-track-histogram-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stream-track-histogram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: The histogram displays the number of tracks that have a certain amount of streams
</figcaption>
</figure>
</div>
</div>
</div>
<p><br>
In order to combat this, I decided to use the median of track engagement distribution to weigh the track release count by year. I chose to use the median because, as seen in <a href="#fig-stream-track-histogram" class="quarto-xref">Figure&nbsp;7</a>, the data is very skewed. This means that using the mean wouldn’t be accurate to the desired value (the middle point of the data). The data seen in <a href="#fig-weighted-track-table" class="quarto-xref">Figure&nbsp;8</a> shows how the track count data is changed by the weight.<br>
</p>
<div class="cell">
<div id="fig-weighted-track-table" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-weighted-track-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">Year</th>
<th style="text-align: right;">Track Count</th>
<th style="text-align: right;">Weighted Track Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2012</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">508622338</td>
</tr>
<tr class="even">
<td style="text-align: right;">2013</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">129252343</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2016</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">552497733</td>
</tr>
<tr class="even">
<td style="text-align: right;">2017</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1837938402</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2018</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2418706680</td>
</tr>
<tr class="even">
<td style="text-align: right;">2019</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2894464488</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2020</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">6656706120</td>
</tr>
<tr class="even">
<td style="text-align: right;">2021</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">2391287886</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2022</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">7941470975</td>
</tr>
<tr class="even">
<td style="text-align: right;">2023</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">10350481533</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2024</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">855469475</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-weighted-track-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Track Count and Weighted Track Count by Year
</figcaption>
</figure>
</div>
</div>
<p><br>
Now, in comparison with the tourism data, we would need to join the two data frames on an <strong>inner join</strong> in order to get all of the years the two have in common. Then, the comparison can be made between the tourist arrivals and the weighted track count (see <a href="#fig-release-tourism-line" class="quarto-xref">Figure&nbsp;9</a>).<br>
<br>
</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-release-tourism-line" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-release-tourism-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="kkl5524Stat184CourseProject_files/figure-html/fig-release-tourism-line-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-release-tourism-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: The red dashed line is the trend line for the scatter plot
</figcaption>
</figure>
</div>
</div>
</div>
<p><br>
Unfortunately, it looks like there is only a weak correlation between the two factors. This is supported by <a href="#fig-correlation-test-table" class="quarto-xref">Figure&nbsp;10</a> that shows the p-value is <strong>0.3235</strong>, which is far greater than 0.05 which means that the correlation is <strong>not statistically significant enough</strong> to disprove the null hypothesis that there is a greater trend between tourism arrivals and K-pop releases.<br>
<br>
Therefore, there is no observable correlation between the two factors.<br>
<br>
</p>
<div class="cell">
<div id="fig-correlation-test-table" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-correlation-test-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Correlation Coefficient</td>
<td style="text-align: right;">-0.1230</td>
</tr>
<tr class="even">
<td style="text-align: left;">T-Value</td>
<td style="text-align: right;">-0.9950</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Degrees of Freedom</td>
<td style="text-align: right;">64.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">P-Value</td>
<td style="text-align: right;">0.3235</td>
</tr>
<tr class="odd">
<td style="text-align: left;">95% Confidence Interval Lower Bound</td>
<td style="text-align: right;">-0.3550</td>
</tr>
<tr class="even">
<td style="text-align: left;">95% Confidence Interval Upper Bound</td>
<td style="text-align: right;">0.1220</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-correlation-test-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Pearson’s Product-Moment Correlation Test Results of K-pop Weighted Tracks vs.&nbsp;Tourism
</figcaption>
</figure>
</div>
</div>
<p><br>
However, the pure comparison of two factors doesn’t tell the whole story. Looking at the graphs by region (see <a href="#fig-region-release-tourism-line" class="quarto-xref">Figure&nbsp;11</a>), the data points are tighter to the trend line compared the original graph (see <a href="#fig-release-tourism-line" class="quarto-xref">Figure&nbsp;9</a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-region-release-tourism-line" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-region-release-tourism-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="kkl5524Stat184CourseProject_files/figure-html/fig-region-release-tourism-line-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-region-release-tourism-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Each graph represents a region with somewhat more correlation
</figcaption>
</figure>
</div>
</div>
</div>
<p><br>
When looking closer at the correlation test results of the Pearson’s Product-Moment Correlation Test, we can see that the p-values are still all greater than 0.05 but there are subtle differences (see <a href="#fig-region-cor-table" class="quarto-xref">Figure&nbsp;12</a>).<br>
<br>
</p>
<div class="cell">
<div id="fig-region-cor-table" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-region-cor-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Region</th>
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Africa</td>
<td style="text-align: left;">Correlation Coefficient</td>
<td style="text-align: right;">-0.0870</td>
</tr>
<tr class="even">
<td style="text-align: left;">Africa</td>
<td style="text-align: left;">P-Value</td>
<td style="text-align: right;">0.7988</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Americas</td>
<td style="text-align: left;">Correlation Coefficient</td>
<td style="text-align: right;">-0.1700</td>
</tr>
<tr class="even">
<td style="text-align: left;">Americas</td>
<td style="text-align: left;">P-Value</td>
<td style="text-align: right;">0.6166</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Asia</td>
<td style="text-align: left;">Correlation Coefficient</td>
<td style="text-align: right;">-0.5120</td>
</tr>
<tr class="even">
<td style="text-align: left;">Asia</td>
<td style="text-align: left;">P-Value</td>
<td style="text-align: right;">0.1077</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Europe</td>
<td style="text-align: left;">Correlation Coefficient</td>
<td style="text-align: right;">-0.3550</td>
</tr>
<tr class="even">
<td style="text-align: left;">Europe</td>
<td style="text-align: left;">P-Value</td>
<td style="text-align: right;">0.2842</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Middle East</td>
<td style="text-align: left;">Correlation Coefficient</td>
<td style="text-align: right;">0.1640</td>
</tr>
<tr class="even">
<td style="text-align: left;">Middle East</td>
<td style="text-align: left;">P-Value</td>
<td style="text-align: right;">0.6299</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Other</td>
<td style="text-align: left;">Correlation Coefficient</td>
<td style="text-align: right;">-0.5330</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other</td>
<td style="text-align: left;">P-Value</td>
<td style="text-align: right;">0.0912</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-region-cor-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Correlation Test Results of K-pop Weighted Tracks vs.&nbsp;Tourism by Region
</figcaption>
</figure>
</div>
</div>
<p><br>
Below is a graphic view of the different correlation coefficients.<br>
<br>
</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cor-comparison-table" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cor-comparison-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="kkl5524Stat184CourseProject_files/figure-html/fig-cor-comparison-table-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cor-comparison-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: The overall correlation coefficient is on the right
</figcaption>
</figure>
</div>
</div>
</div>
<p><br>
As you can see, there are a few main factors that caused the overall correlation coefficient to be so high, namely Africa, the Americas, and the Middle East. While the other three are high in comparison to the threshold, the distribution is clearly visible (see <a href="#fig-cor-comparison-table" class="quarto-xref">Figure&nbsp;13</a>).<br>
<br>
</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>This exploratory data analysis set out to examine the relationship between K-pop’s global popularity and international tourism arrivals to South Korea. Two guiding hypotheses were posed: that there is a correlation between international streaming trends and tourism, and that Asian regions would show the strongest connection.<br>
</p>
<p>After compiling, cleaning, and transforming datasets from Spotify, YouTube, Kaggle, and UNWTO, the data was explored through weighted metrics of K-pop track releases and regional tourist arrivals.<br>
</p>
<section id="key-findings" class="level3">
<h3 class="anchored" data-anchor-id="key-findings">Key Findings</h3>
<ul>
<li>There is <strong>no statistically significant correlation</strong> between the number of K-pop releases (weighted by engagement) and inbound tourism to South Korea, as shown by a Pearson correlation coefficient of -0.123 and a p-value of 0.3235 (see <a href="#fig-correlation-test-table" class="quarto-xref">Figure&nbsp;10</a>)</li>
<li>Regional breakdowns revealed <strong>stronger visual patterns</strong>, especially in regions like Asia and Europe, though even these lacked statistically significant p-values below 0.05 (see <a href="#fig-cor-comparison-table" class="quarto-xref">Figure&nbsp;13</a>)</li>
<li>Artists like BTS, BLACKPINK, and TWICE were among the <strong>most influential</strong> in terms of total engagement (see <a href="#fig-kpop-popular-artist-table" class="quarto-xref">Figure&nbsp;4</a>)<br>
</li>
</ul>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<p>Although the hypothesis of a direct correlation was not supported by statistical evidence, regional variances suggest more nuanced trends for further investigation. It’s possible that other variables (like marketing or visa policies) influence the effect of K-pop on tourism.<br>
</p>
<p>The lack of significance may also reflect the <strong>lagging nature</strong> of tourism data or the limited scope of available streaming platforms used in the analysis. Additionally, international travel is influenced by numerous external factors such as geopolitical conditions, economic stability, and global events that could obscure the effects of cultural exports like music.<br>
</p>
</section>
<section id="future-research" class="level3">
<h3 class="anchored" data-anchor-id="future-research">Future Research</h3>
<p>Future analyses could benefit from a longer-term dataset of music releases and tourism statistics beyond 2024 as well as more data points (either more frequent or with individual countries rather than regions). Additionally, there could be cause to find more data on where specific artist fanbases are located.<br>
</p>
<p>Overall, this project illustrates the complexity of linking cultural phenomena like K-pop to economic indicators like tourism while also showing that culture-driven interests do not always cause immediate economic impact. Still, with K-pop’s continuing global reach and growing popularity in the mainstream, there remains potential for more direct connections to emerge over time.<br>
<br>
</p>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Arias, N. I. A. (2023). 400+ K-Pop Groups Dataset. Distributed by Kaggle. Retrieved August 12, 2025. <a href="https://www.kaggle.com/datasets/nicolsalayoarias/kpop-groups-dataset" class="uri">https://www.kaggle.com/datasets/nicolsalayoarias/kpop-groups-dataset</a><br>
</p>
<p>Arias, N. I. A. (2023). 1700+ K-Pop Idols Dataset. Distributed by Kaggle. Retrieved August 12, 2025. <a href="https://www.kaggle.com/datasets/nicolsalayoarias/all-kpop-idols" class="uri">https://www.kaggle.com/datasets/nicolsalayoarias/all-kpop-idols</a><br>
</p>
<p>Elgiriyewithana, N. (2024). Most Streamed Spotify Songs 2024. Distributed by Kaggle. Retrieved August 12, 2025. <a href="https://www.kaggle.com/datasets/nelgiriyewithana/most-streamed-spotify-songs-2024" class="uri">https://www.kaggle.com/datasets/nelgiriyewithana/most-streamed-spotify-songs-2024</a><br>
</p>
<p>Hong, S., &amp; Seo, D. (2025, February). [Yanolja Research] Brief Vol.5. Korea’s Inbound and Outbound Tourism Performance in 2024. Seoul; Yanolja Research.<br>
</p>
<p>Our Culture Mag, Partners. (2025, March 30). Global consumer spending on leisure activities reaches new highs as post-pandemic experiences boom in 2025. Our Culture. <a href="https://ourculturemag.com/2025/03/30/global-consumer-spending-on-leisure-activities-reaches-new-highs-as-post-pandemic-experiences-boom-in-2025/" class="uri">https://ourculturemag.com/2025/03/30/global-consumer-spending-on-leisure-activities-reaches-new-highs-as-post-pandemic-experiences-boom-in-2025/</a><br>
</p>
<p>Pangarkar, T. (2025, January 14). Online video platform statistics and facts (2025). Market.us Scoop. <a href="https://scoop.market.us/online-video-platform-statistics/" class="uri">https://scoop.market.us/online-video-platform-statistics/</a><br>
</p>
<p>Spotify. (2025, July 29). Spotify reports second quarter 2025 earnings. Spotify. <a href="https://newsroom.spotify.com/2025-07-29/spotify-reports-second-quarter-2025-earnings/" class="uri">https://newsroom.spotify.com/2025-07-29/spotify-reports-second-quarter-2025-earnings/</a><br>
</p>
<p>Spotify. (n.d.). Where is Spotify available?. Spotify. <a href="https://support.spotify.com/us/article/where-spotify-is-available/" class="uri">https://support.spotify.com/us/article/where-spotify-is-available/</a><br>
</p>
<p>UN Tourism. (2024, January 31). Tourism Statistics Database. Distributed by UN Tourism. Retrieved August 12, 2025. <a href="https://www.unwto.org/tourism-statistics/tourism-statistics-database" class="uri">https://www.unwto.org/tourism-statistics/tourism-statistics-database</a><br>
<br>
</p>
</section>
<section id="code-appendix" class="level2">
<h2 class="anchored" data-anchor-id="code-appendix">Code Appendix</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Style guide: Tidyverse</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/Original_UN_Tourism_Data.png"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/Yanolja_Research_Chart.png"</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>KPopGroupsRaw <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"datasets/kpopgroups.csv"</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>KPopIdolsRaw <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"datasets/kpopidolsv3.csv"</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>KPopArtists <span class="ot">&lt;-</span> KPopGroupsRaw <span class="sc">%&gt;%</span> </span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">full_join</span>(KPopIdolsRaw, <span class="at">by=</span><span class="fu">join_by</span>(<span class="st">"Name"</span><span class="sc">==</span><span class="st">"Stage.Name"</span>))</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>KPopArtists <span class="ot">&lt;-</span> KPopArtists <span class="sc">%&gt;%</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"Name"</span>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>Spotify2024Raw <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"datasets/Most Streamed Spotify Songs 2024.csv"</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>Spotify2024 <span class="ot">&lt;-</span> Spotify2024Raw <span class="sc">%&gt;%</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(Release.Date, <span class="at">sep=</span><span class="st">"/"</span>, <span class="at">into=</span><span class="fu">c</span>(<span class="st">"Month"</span>, <span class="st">"Day"</span>, <span class="st">"Year"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"Track"</span>, <span class="st">"Artist"</span>, <span class="st">"Year"</span>, <span class="st">"Spotify.Streams"</span>, <span class="st">"YouTube.Likes"</span>)  <span class="sc">%&gt;%</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">Spotify.Streams =</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">","</span>,<span class="st">""</span>, Spotify.Streams)),</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">YouTube.Likes =</span> <span class="fu">as.numeric</span>(<span class="fu">gsub</span>(<span class="st">","</span>,<span class="st">""</span>, YouTube.Likes)),</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">Year =</span> <span class="fu">as.numeric</span>(Year)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Spotify.Streams), <span class="sc">!</span><span class="fu">is.na</span>(YouTube.Likes), <span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"NA"</span>, Spotify.Streams), <span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"NA"</span>, YouTube.Likes))</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>KPopSpotify <span class="ot">&lt;-</span> KPopArtists <span class="sc">%&gt;%</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(Spotify2024, <span class="at">by=</span><span class="fu">join_by</span>(<span class="st">"Name"</span><span class="sc">==</span><span class="st">"Artist"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Spotify.Streams))</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>KPopSpotifyDF <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(KPopSpotify <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">5</span>))</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(KPopSpotifyDF, </span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Top 5 Tracks by Spotify Streams (and associated data)"</span>,</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Artist Name"</span>, <span class="st">"Track Name"</span>, <span class="st">"Release Year"</span>, <span class="st">"Spotify Streams"</span>, <span class="st">"YouTube Likes"</span>))</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>PopularArtists <span class="ot">&lt;-</span> KPopSpotify <span class="sc">%&gt;%</span></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Name) <span class="sc">%&gt;%</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_spotify =</span> <span class="fu">sum</span>(Spotify.Streams),</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_youtube =</span> <span class="fu">sum</span>(YouTube.Likes)</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_engagement =</span> total_spotify<span class="sc">+</span>total_youtube) <span class="sc">%&gt;%</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_engagement)) <span class="sc">%&gt;%</span></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"Name"</span>, <span class="st">"total_engagement"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Total_Engagement =</span> total_engagement)</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>PopularArtistsDF <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(PopularArtists <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">10</span>))</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(PopularArtistsDF, </span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Top 10 K-Pop Artists by Total Engagement on Spotify and YouTube"</span>,</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Artist Name"</span>, <span class="st">"Total Engagement"</span>))</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>TourismStatisticsRaw <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"datasets/south korea visitor arrivals (thousands).csv"</span>)</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>TourismStatistics <span class="ot">&lt;-</span> TourismStatisticsRaw <span class="sc">%&gt;%</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_arrivals =</span> arrivals<span class="sc">*</span><span class="dv">1000</span>)</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>TourismStatistics <span class="sc">%&gt;%</span></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>year, <span class="at">y=</span>arrivals)) <span class="sc">+</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">color=</span>region)) <span class="sc">+</span></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">n.breaks=</span><span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">1995</span><span class="sc">:</span><span class="dv">2024</span>)) <span class="sc">+</span></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">45</span>, <span class="at">vjust=</span><span class="dv">1</span>, <span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>    <span class="at">x=</span><span class="st">"Year"</span>, </span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>    <span class="at">y=</span><span class="st">"Arrivals (in thousands)"</span>, </span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>    <span class="at">title=</span><span class="st">"Tourism Traffic Inbound to South Korea from 1995-2024"</span></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>Spotify2024 <span class="sc">%&gt;%</span></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>    <span class="at">track_count =</span> <span class="fu">NROW</span>(Track)</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Year, <span class="at">y=</span>track_count)) <span class="sc">+</span></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">1987</span><span class="sc">:</span><span class="dv">2024</span>)) <span class="sc">+</span></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">45</span>, <span class="at">vjust=</span><span class="dv">1</span>, <span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>    <span class="at">x=</span><span class="st">"Year"</span>, </span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>    <span class="at">y=</span><span class="st">"Track Count"</span>, </span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>    <span class="at">title=</span><span class="st">"Number of Tracks made by K-pop Artists from 1987-2024"</span></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>Spotify2024 <span class="sc">%&gt;%</span> </span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Spotify.Streams)) <span class="sc">+</span></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>    <span class="at">x=</span><span class="st">"Spotify Streams"</span>, </span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>    <span class="at">y=</span><span class="st">"Number of Tracks"</span>, </span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>    <span class="at">title=</span><span class="st">"Track Distribution of Streams"</span></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>WeightedTracks <span class="ot">&lt;-</span> KPopSpotify <span class="sc">%&gt;%</span> </span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_engagement =</span> Spotify.Streams <span class="sc">+</span> YouTube.Likes) <span class="sc">%&gt;%</span></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>    <span class="at">track_count =</span> <span class="fu">n</span>(),</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_engagement =</span> <span class="fu">median</span>(total_engagement, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weighted_track_count =</span> track_count <span class="sc">*</span> median_engagement) <span class="sc">%&gt;%</span> </span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"Year"</span>, <span class="st">"track_count"</span>, <span class="st">"weighted_track_count"</span>)</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>WeightedTracksDF <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(WeightedTracks)</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(WeightedTracksDF, </span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Track Count and Weighted Track Count by Year"</span>,</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Year"</span>, <span class="st">"Track Count"</span>, <span class="st">"Weighted Track Count"</span>))</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>ReleasesTourismComparison <span class="ot">&lt;-</span> WeightedTracks <span class="sc">%&gt;%</span> </span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(TourismStatistics, <span class="at">by=</span><span class="fu">join_by</span>(<span class="st">"Year"</span> <span class="sc">==</span> <span class="st">"year"</span>))</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>cor_value <span class="ot">&lt;-</span> <span class="fu">cor</span>(ReleasesTourismComparison<span class="sc">$</span>weighted_track_count, ReleasesTourismComparison<span class="sc">$</span>arrivals)</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>ReleasesTourismComparison <span class="sc">%&gt;%</span></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>weighted_track_count, <span class="at">y=</span>arrivals)) <span class="sc">+</span></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"blue"</span>, <span class="at">size=</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">color=</span><span class="st">"red"</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>    <span class="at">x=</span><span class="st">"Weighted Track Count"</span>,</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>    <span class="at">y=</span><span class="st">"Tourist Arrivals"</span>, </span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"K-pop Releases vs. Tourism ( r ="</span>, <span class="fu">round</span>(cor_value, <span class="dv">3</span>), <span class="st">")"</span>)</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>cor_test_result <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(ReleasesTourismComparison<span class="sc">$</span>weighted_track_count, ReleasesTourismComparison<span class="sc">$</span>arrivals)</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>VerticalCorTestDF <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>  <span class="at">Statistic =</span> <span class="fu">c</span>(</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Correlation Coefficient"</span>,</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>    <span class="st">"T-Value"</span>,</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Degrees of Freedom"</span>,</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>    <span class="st">"P-Value"</span>,</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>    <span class="st">"95% Confidence Interval Lower Bound"</span>,</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>    <span class="st">"95% Confidence Interval Upper Bound"</span></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value =</span> <span class="fu">c</span>(</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>    <span class="fu">round</span>(cor_test_result<span class="sc">$</span>estimate, <span class="dv">3</span>),</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a>    <span class="fu">round</span>(cor_test_result<span class="sc">$</span>statistic, <span class="dv">3</span>),</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a>    cor_test_result<span class="sc">$</span>parameter,</span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>    <span class="fu">round</span>(cor_test_result<span class="sc">$</span>p.value, <span class="dv">4</span>),</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>    <span class="fu">round</span>(cor_test_result<span class="sc">$</span>conf.int[<span class="dv">1</span>], <span class="dv">3</span>),</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>    <span class="fu">round</span>(cor_test_result<span class="sc">$</span>conf.int[<span class="dv">2</span>], <span class="dv">3</span>)</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(VerticalCorTestDF, </span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Pearson’s Product-Moment Correlation Test Results of K-pop Weighted Tracks vs. Tourism"</span></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>ReleasesTourismComparison <span class="sc">%&gt;%</span> </span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> weighted_track_count, <span class="at">y =</span> arrivals)) <span class="sc">+</span></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> region, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span> </span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Weighted Track Count"</span>,</span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Tourism Arrivals"</span>,</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Tourism Arrivals vs. Weighted K-pop Track Count by Region"</span>,</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Scatter plots with linear regression trend lines"</span></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">45</span>, <span class="at">vjust=</span><span class="dv">1</span>, <span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a><span class="co"># Credit to user ek-g at https://stackoverflow.com/questions/62359251/using-group-modify-to-apply-function-to-grouped-dataframe on Reddit for the original idea of using group_modify as an iterative function.</span></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>RegionCorDetailedDF <span class="ot">&lt;-</span> ReleasesTourismComparison <span class="sc">%&gt;%</span></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_modify</span>(<span class="sc">~</span> {</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>    df <span class="ot">&lt;-</span> <span class="fu">filter</span>(.x, <span class="sc">!</span><span class="fu">is.na</span>(weighted_track_count), <span class="sc">!</span><span class="fu">is.na</span>(arrivals))</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">nrow</span>(df) <span class="sc">&gt;=</span> <span class="dv">2</span> <span class="sc">&amp;&amp;</span> <span class="fu">sd</span>(df<span class="sc">$</span>weighted_track_count) <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;&amp;</span> <span class="fu">sd</span>(df<span class="sc">$</span>arrivals) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>      test <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(df<span class="sc">$</span>weighted_track_count, df<span class="sc">$</span>arrivals)</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>      <span class="fu">tibble</span>(</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>        <span class="at">Statistic =</span> <span class="fu">c</span>(<span class="st">"Correlation Coefficient"</span>, <span class="st">"P-Value"</span>),</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a>        <span class="at">Value =</span> <span class="fu">c</span>(<span class="fu">round</span>(test<span class="sc">$</span>estimate, <span class="dv">3</span>), <span class="fu">round</span>(test<span class="sc">$</span>p.value, <span class="dv">4</span>))</span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a>  }) <span class="sc">%&gt;%</span></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(RegionCorDetailedDF, </span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Correlation Test Results of K-pop Weighted Tracks vs. Tourism by Region"</span>,</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Region"</span>, <span class="st">"Statistic"</span>, <span class="st">"Value"</span>)</span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>      ) </span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a>RegionCorDetailedDF <span class="sc">%&gt;%</span> </span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_row</span>(<span class="at">region=</span><span class="st">"Overall"</span>, <span class="at">Statistic=</span><span class="st">"Correlation Coefficient"</span>, <span class="at">Value=</span><span class="sc">-</span><span class="fl">0.123</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_row</span>(<span class="at">region=</span><span class="st">"Overall"</span>, <span class="at">Statistic=</span><span class="st">"P-Value"</span>, <span class="at">Value=</span><span class="fl">0.3235</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Statistic<span class="sc">==</span><span class="st">"P-Value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>region, <span class="at">y=</span>Value)) <span class="sc">+</span></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">'identity'</span>) <span class="sc">+</span></span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Region"</span>,</span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Value"</span>,</span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Correlation Coefficients based on Region"</span></span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>